# Generated by Django 4.1.6 on 2023-02-07 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="short_description",
            new_name="shortDescription",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="purchase_date",
            new_name="purchaseDate",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="purchase_time",
            new_name="purchaseTime",
        ),
    ]
