# Generated by Django 4.1.6 on 2023-02-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
