# Generated by Django 4.1.6 on 2023-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_receipt_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="points",
        ),
    ]
