# Generated by Django 4.1.6 on 2023-02-07 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_rename_short_description_item_shortdescription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="receipt",
        ),
    ]
