# Generated by Django 4.1.6 on 2023-02-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_item_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="receipt",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="backend.receipt",
            ),
            preserve_default=False,
        ),
    ]
