# Generated by Django 4.1.6 on 2023-02-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_item_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="receipt",
            field=models.ForeignKey(
                default="12",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="backend.receipt",
            ),
        ),
    ]
