# Generated by Django 4.1.6 on 2023-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_item_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="items",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
